name: tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.3', '8.4', '8.5']

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Node Dependencies
        run: npm i

      - name: Install Playwright Dependencies
        run: npx playwright install

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Build Assets
        run: npm run build

      - name: Tests
        run: ./vendor/bin/pest

  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm install

      - name: Run Pint
        run: composer lint

      - name: Format Frontend
        run: npm run format

      - name: Lint Frontend
        run: npm run lint

  deploy:
    runs-on: ubuntu-latest
    needs: [tests, lint]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Trigger Laravel Cloud Deploy Webhook
        run: curl -X POST "$LARAVEL_CLOUD_DEPLOY_WEBHOOK"
        env:
          LARAVEL_CLOUD_DEPLOY_WEBHOOK: ${{ secrets.LARAVEL_CLOUD_DEPLOY_WEBHOOK }}
